---
title: Lit Tracker
author: 'Matt Kmiecik'
date: '`r Sys.Date()`'
slug: lit-tracker
categories: []
tags: []
editor_options: 
  chunk_output_type: console
---

This post serves as my daily literature tracker. My goal is to sit and read at least 1 paper per day Monday-Friday. 

Here are the packages used for this post:

```{r}
library(tidyverse)
library(readxl)
library(httr)
```

```{r}
# inspired by: https://community.rstudio.com/t/read-xlsx-from-github/9386/3
github_link <- 
  "https://github.com/mkmiecik14/lit-tracker/blob/main/lit-tracker.xlsx?raw=true"

temp_file <- tempfile(fileext = ".xlsx")
req <- 
  GET(
    github_link, 
    write_disk(path = temp_file)# write result to disk
    )
lit_data <- readxl::read_excel(temp_file)
```

```{r}
# Calculating features
init_date <- as.Date(lit_data$date[1])
today <- as.Date(Sys.time())
main_data <- 
  tibble(
    date = seq.Date(from = init_date, to = today, by = "days"),
    week = lubridate::week(date),
    day = lubridate::wday(date, label = TRUE)
    ) %>%
  left_join(., lit_data, by = "date") %>%
  mutate(
    read = ifelse(is.na(citation), 0, 1),
    total = cumsum(read)
  )
```

```{r}
# Plot of cumulative reads
ggplot(main_data, aes(date, total)) +
  geom_point() +
  geom_path() +
  labs(x = "Date", y = "Cumulative Reads") +
  theme_bw()
```

```{r}
# next here is a plot of reads per day of the week
```
